'use strict';

// Rebuilds mockup/slides/ (page images + slides-data.js text) from the BTC data pack PDFs.
// Needs poppler's pdftotext and pdftoppm on PATH. Usage: node codebase/build-slides.cjs

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const ROOT = path.resolve(__dirname, '..');
const PACK = path.join(ROOT, 'data', 'local', 'hackathon-context', 'data', 'vlearn-pack', 'slides');
const OUT = path.join(ROOT, 'mockup', 'slides');
const DECKS = { 1: 'd1', 2: 'd2' };

const clean = line => line.replace(/\s+/g, ' ').trim()
  .replace(/^A(?=[A-ZĐÂĂÊÔƠƯ][a-zà-ỹ])/, ''); // "HACKATHON" watermark letter glued to a line
const isNoise = line => line.length < 3 || /^([A-Z]\s*){1,3}$/.test(line) || /^AI IN ACTION/i.test(line);

const result = {};
for (const [day, deck] of Object.entries(DECKS)) {
  const pdf = path.join(PACK, `${deck}-slide-hackathon.pdf`);
  if (!fs.existsSync(pdf)) throw new Error(`Missing ${pdf}. Clone the BTC repo into data/local/hackathon-context first.`);
  const txt = path.join(os.tmpdir(), `${deck}-slides.txt`);
  execFileSync('pdftotext', ['-enc', 'UTF-8', pdf, txt]);
  fs.mkdirSync(path.join(OUT, deck), { recursive: true });
  execFileSync('pdftoppm', ['-jpeg', '-jpegopt', 'quality=78', '-scale-to', '1280', pdf, path.join(OUT, deck, 'p')]);
  const pages = fs.readFileSync(txt, 'utf8').split('\f').slice(0, -1);
  result[day] = pages.map((raw, index) => {
    const merged = [];
    for (const line of raw.split(/\r?\n/).map(clean).filter(line => !isNoise(line))) {
      const previous = merged[merged.length - 1];
      // Join lines that pdftotext wrapped mid-sentence.
      if (previous && !/[.:!?»”")]$/.test(previous) && /^[a-zà-ỹ(]/.test(line)) merged[merged.length - 1] = `${previous} ${line}`;
      else merged.push(line);
    }
    const page = index + 1;
    return { page, title: merged[0] || `Trang ${page}`, bullets: merged.slice(1).map(bullet => bullet.replace(/^[•●▪\-–]\s*/, '')).filter(Boolean), image: `slides/${deck}/p-${String(page).padStart(2, '0')}.jpg` };
  });
  console.log(`Day ${day}: ${result[day].length} pages`);
}
fs.writeFileSync(path.join(OUT, 'slides-data.js'), `'use strict';\n// Generated by codebase/build-slides.cjs from the BTC data pack PDFs (pdftotext + pdftoppm).\n// Text is used for the AI tutor, quiz source and "Đọc nội dung slide"; images are what the learner sees.\nconst PDF_SLIDES=${JSON.stringify(result, null, 1)};\n`);
console.log(`Wrote ${path.relative(ROOT, OUT)}`);
