
const seed=[
{id:'1',session:'Buổi 03 · LLM Foundation',date:'17/09/2026',title:'RAG và Fine-tuning khác nhau thế nào?',source:'Từ chat Tutor',question:'Khi nào nên dùng RAG thay vì fine-tuning cho một trợ lý học tập?',slide:'Slide 12',src:'T03 · LLM Foundation · trang 12',summary:['RAG đưa tài liệu bên ngoài vào ngữ cảnh khi trả lời.','Fine-tuning thay đổi tham số mô hình bằng dữ liệu huấn luyện.','RAG phù hợp khi kiến thức thay đổi hoặc cần dẫn nguồn.'],status:'need',quiz:[['RAG bổ sung kiến thức bằng cách nào?',['Huấn luyện lại toàn bộ tham số','Đưa tài liệu liên quan vào ngữ cảnh','Xóa kiến thức cũ','Đổi tokenizer'],1,'RAG tìm tài liệu liên quan rồi đưa vào context để trả lời.'],['Trường hợp nào phù hợp với RAG hơn?',['Thông tin nội bộ thay đổi thường xuyên','Đổi phong cách viết','Giảm tài liệu','Không có nguồn'],0,'RAG cập nhật nguồn mà không cần fine-tune lại.'],['Điểm mạnh của RAG trong tutor?',['Đúng 100%','Có thể trích dẫn nguồn','Không cần dữ liệu','Không cần kiểm thử'],1,'Tutor có thể dẫn lại đoạn tài liệu để đối chiếu.']]},
{id:'2',session:'Buổi 03 · LLM Foundation',date:'16/09/2026',title:'Prompt có cấu trúc',source:'Đánh dấu slide',question:'Tôi đã đánh dấu phần nói về cấu trúc của một prompt tốt.',slide:'Slide 18',src:'T03 · LLM Foundation · trang 18',summary:['Nêu rõ vai trò và mục tiêu.','Cung cấp ngữ cảnh cần thiết.','Mô tả format đầu ra và tiêu chí chất lượng.'],status:'need',quiz:[['Prompt có cấu trúc nên nêu rõ điều gì?',['Chỉ câu hỏi','Vai trò, mục tiêu, ngữ cảnh và format','Tên học viên','Số token'],1,'Cấu trúc rõ giúp mô hình hiểu nhiệm vụ và đầu ra.'],['Vì sao cần nêu format đầu ra?',['Để dài hơn','Để kết quả nhất quán','Để đổi chủ đề','Không có tác dụng'],1,'Format giúp đầu ra ổn định và dễ kiểm tra.'],['Điều nào không bắt buộc trong mọi prompt?',['Mục tiêu','Ngữ cảnh','Tên thật học viên','Yêu cầu đầu ra'],2,'Tên người học chỉ cần khi thực sự liên quan.']]},
{id:'3',session:'Buổi 02 · Xác định bài toán AI',date:'15/09/2026',title:'Chọn mức tự động hóa phù hợp',source:'Từ chat Tutor',question:'Mức tự động hóa nào phù hợp khi chi phí sai rất cao?',slide:'Slide 25',src:'T02 · Xác định bài toán AI · trang 25',summary:['Xét lợi ích và cost of error.','Việc có hậu quả lớn nên giữ bước duyệt người.','Nêu rõ ranh giới AI và người dùng.'],status:'need',quiz:[['Khi chi phí sai cao, thiết kế nào an toàn hơn?',['Tự động hoàn toàn','Có người kiểm tra trước quyết định','Bỏ qua không chắc chắn','Tăng độ dài'],1,'Human-in-the-loop giảm hậu quả khi AI sai.'],['Cost of error là gì?',['Chi phí giao diện','Thiệt hại khi quyết định sai','Thời gian tải','Số câu quiz'],1,'Đó là hậu quả phát sinh khi quyết định AI sai.'],['Non-goal giúp làm gì?',['Mở rộng tính năng','Nêu việc chưa giải quyết','Tạo dữ liệu','Đổi màu'],1,'Non-goal đặt ranh giới cho prototype.']]},
{id:'4',session:'Buổi 02 · Xác định bài toán AI',date:'14/09/2026',title:'Problem statement một câu',source:'Từ chat Tutor',question:'Tôi hỏi tutor cách viết problem statement cho bài toán nhóm.',slide:'Slide 21',src:'T02 · Xác định bài toán AI · trang 21',summary:['Chỉ rõ user, job, quyết định AI và kết quả.','Pain mô tả hành vi và hậu quả quan sát được.','Tránh bắt đầu bằng giải pháp.'],status:'done',quiz:[['Problem statement nên bắt đầu từ đâu?',['Tên model','Người dùng và công việc','Màu giao diện','API'],1,'Bắt đầu từ user và job để bám vấn đề thật.'],['Điều nào nên tránh?',['Mô tả hậu quả','Nêu quyết định','Bắt đầu bằng công nghệ','Xác định user'],2,'Công nghệ là phương tiện, không phải vấn đề.'],['Lát cắt tốt có bao nhiêu quyết định AI trung tâm?',['Một','Năm','Không giới hạn','Tùy nhóm'],0,'Một quyết định giúp prototype tập trung và đo được.']]},
{id:'5',session:'Buổi 01 · Foundation',date:'12/09/2026',title:'Transformer và attention',source:'Đánh dấu slide',question:'Tôi đánh dấu sơ đồ attention vì chưa hiểu mô hình tập trung vào token nào.',slide:'Slide 9',src:'T01 · Foundation · trang 9',summary:['Attention tính mức liên quan giữa các token.','Query, key và value tham gia phép tính.','Cần nhìn cả ngữ cảnh, không chỉ một token.'],status:'missing',quiz:[]},
{id:'6',session:'Buổi 01 · Foundation',date:'11/09/2026',title:'LLM dự đoán token tiếp theo',source:'Từ chat Tutor',question:'LLM thực sự “hiểu” câu hay chỉ dự đoán token tiếp theo?',slide:'Slide 15',src:'T01 · Foundation · trang 15',summary:['LLM sinh chuỗi bằng dự đoán token tiếp theo.','Hành vi có vẻ hiểu xuất hiện từ mẫu và ngữ cảnh.','Cần kiểm tra đầu ra thay vì giả định mô hình hiểu như người.'],status:'done',quiz:[['Cơ chế sinh cơ bản của LLM là gì?',['Dự đoán token tiếp theo','Tra cứu đáp án','Đọc suy nghĩ','Luật cố định'],0,'LLM dự đoán token tiếp theo dựa trên ngữ cảnh.'],['Vì sao cần kiểm tra đầu ra?',['Mô hình luôn sai','Câu trôi chảy vẫn có thể không đúng','Để dài hơn','Vì không có context'],1,'Câu trả lời trôi chảy vẫn có thể không được nguồn hỗ trợ.'],['Context ảnh hưởng điều gì?',['Cách chọn token tiếp theo','Màu màn hình','Tài khoản','Tốc độ mạng'],0,'Context cung cấp tín hiệu để dự đoán phù hợp hơn.']]}
];
seed[0].quiz.push(['Câu nào mô tả đúng giới hạn của RAG?',['RAG tự động loại bỏ mọi hallucination','RAG vẫn cần đánh giá chất lượng nguồn và câu trả lời','RAG không cần truy xuất tài liệu','RAG luôn nhanh hơn mọi mô hình'],1,'RAG giúp grounding nhưng vẫn cần kiểm tra nguồn và đầu ra.'],['Nếu tài liệu nguồn không đủ ngữ cảnh, VinMark nên làm gì?',['Tự đoán phần còn thiếu','Báo chưa đủ nguồn và yêu cầu bổ sung','Tạo quiz bất kỳ','Xóa câu hỏi'],1,'Agent cần biết-mình-không-biết thay vì tạo quiz không có căn cứ.']);
seed[1].quiz.push(['Khi prompt có nhiều yêu cầu, nên làm gì?',['Gộp tất cả không cần thứ tự','Tách rõ nhiệm vụ và tiêu chí đầu ra','Bỏ phần ngữ cảnh','Chỉ viết một từ khóa'],1,'Tách nhiệm vụ giúp người dùng kiểm tra từng kết quả.']);
